version: '2'
 
services:
 web:
   restart: always
   build: ./web
   expose:
     - "8000"
   volumes:
     - /usr/src/app/static
     - /usr/src/app/media
   command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app
   depends_on:
     - mongo

 nginx:
   restart: always
   build: ./nginx
   ports:
     - "80:80"
   volumes:
     - /www/static
   volumes_from:
     - web
   depends_on:
     - web

 mongo:
   image: mongo:3.4.0
   restart: always

volumes:
  redis:
